service: ${self:custom.serviceName}
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, "us-east-2"}
  environment: ${file(./aws-env.yml)}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${self:custom.serviceName}*'

custom:
  serviceName: ryzeup-serverless

functions:
  order-create:
    handler: src/handler/http/order-create.handler
    events:
      - httpApi:
          path: /
          method: post
  sheet-migrate:
    handler: src/handler/schedule/sheet-migrate.handler
    events:
      - schedule: rate(3 days)
    timeout: 300

plugins:
  - serverless-plugin-typescript
